name: Dev ADF

on: 
  pull_request:
    branches:
      - dev
      
permissions:
      id-token: write
      contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.DEVRESOURCEGROUP }} # (6) your target ADF resource group name
          dataFactoryName: ${{ secrets.DEVADF }} # (7) your target ADF name
      
