name: Dev ADF

on: 
  pull_request:
     types:
      - closed
     branches:
      - dev
      - qa
permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
# Installs Node and the npm packages saved in your package.json file in the build
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14.x
        
      - name: install ADF Utilities package
        run: npm install
        working-directory: ${{github.workspace}}/ADFroot/build  # (1) provide the folder location of the package.json file

      - name: Validate
        run: npm run build validate ${{github.workspace}}/ADFroot/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.DEVRESOURCEGROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DEVADF }} # (2) The validate command needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance 
        working-directory: ${{github.workspace}}/ADFroot/build
 

      - name: Validate and Generate ARM template
        run: npm run build export ${{github.workspace}}/ADFroot/ /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.DEVRESOURCEGROUP }}/providers/Microsoft.DataFactory/factories/${{ secrets.DEVADF }} "ExportedArmTemplate"  # (3) The build command, as validate, needs the root folder location of your repository where all the objects are stored. And the 2nd parameter is the resourceID of the ADF instance. The 3rd parameter is the exported ARM template artifact name 
        working-directory: ${{github.workspace}}/ADFroot/build
 
# In order to leverage the artifact in another job, we need to upload it with the upload action 
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ExportedArmTemplate # (4) use the same artifact name you used in the previous export step
          path: ${{github.workspace}}/ADFroot/build/ExportedArmTemplate

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ExportedArmTemplate # (5) Artifact name 
          
          
      - name: View GitHub Workspace
        run: |
          echo "Contents of GitHub Workspace:"
          ls -R ${{ github.workspace }}
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.DEVRESOURCEGROUP }} # (6) your target ADF resource group name
          dataFactoryName: ${{ secrets.DEVADF }} # (7) your target ADF name

  deploy-qa:
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/dev'
    needs: build
    uses: ./.github/workflows/qa-deployement.yml
  
      

    
